---
- name: Retrieve Cisco switch hostname and save to file
  hosts: u1-int-rtr01
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gather Cisco IOS facts
      cisco.ios.ios_facts:
        gather_subset: min
      register: ios_facts

    - name: Save hostname to a text file
      ansible.builtin.copy:
        content: "{{ ios_facts.ansible_facts.ansible_net_hostname }}"
        dest: "/tmp/switch_hostname.txt"
      delegate_to: localhost

    - name: Ensure file is readable
      ansible.builtin.file:
        path: "/tmp/switch_hostname.txt"
        mode: "0644"
      delegate_to: localhost
...
