---
- name: Collect network device hostnames
  hosts: all
  gather_facts: false

  # Set connection parameters
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: "{{ 'eos' if 'eos' in group_names else 'ios' if 'ios' in group_names else omit }}"

  tasks:
    # Collect hostnames from Arista EOS devices
    - name: Get EOS hostname
      arista.eos.eos_command:
        commands: show hostname
      register: hostname_result
      when: "'eos' in group_names"
      ignore_errors: yes

    # Collect hostnames from Cisco IOS devices  
    - name: Get IOS hostname
      cisco.ios.ios_command:
        commands: show running-config | include hostname
      register: hostname_result
      when: "'ios' in group_names"
      ignore_errors: yes

    # Process and display results
    - name: Show hostnames
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Type: {{ 'Arista EOS' if 'eos' in group_names else 'Cisco IOS' }}
          Hostname: {% if 'eos' in group_names and eos_result is defined %}{{ eos_result.stdout[0] | regex_replace('.*hostname is (\\S+).*', '\\1') }}
                   {% elif 'ios' in group_names and ios_result is defined %}{{ ios_result.stdout[0] | regex_replace('hostname (\\S+)', '\\1') }}
                   {% else %}NOT FOUND{% endif %}
      when: "'eos' in group_names or 'ios' in group_names"
