---
- name: Collect network device hostnames
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    # Set network OS based on group membership
    - name: Set ansible_network_os
      set_fact:
        ansible_network_os: >-
          {% if 'eos' in group_names %}arista.eos.eos
          {% elif 'ios' in group_names %}cisco.ios.ios
          {% else %}unknown{% endif %}

    # Collect hostnames from Arista EOS devices
    - name: Get EOS hostname
      arista.eos.eos_command:
        commands: show hostname
      register: eos_hostname
      when: ansible_network_os == 'eos'

    # Collect hostnames from Cisco IOS devices  
    - name: Get IOS hostname
      cisco.ios.ios_command:
        commands: show running-config | include hostname
      register: ios_hostname
      when: ansible_network_os == 'ios'

    # Display results
    - name: Show hostnames
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Type: {{ ansible_network_os | upper }}
          Hostname: {% if ansible_network_os == 'eos' %}{{ eos_hostname.stdout[0] | regex_replace('.*hostname is (\\S+).*', '\\1') }}
                   {% elif ansible_network_os == 'ios' %}{{ ios_hostname.stdout[0] | regex_replace('hostname (\\S+)', '\\1') }}
                   {% else %}Unknown device type{% endif %}
      when: ansible_network_os != 'unknown'
