---
- name: Get Cisco device hostname using show command
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show command to get hostname
      cisco.ios.ios_command:
        commands: show run | include hostname
      register: show_hostname

    - name: Display hostname
      debug:
        msg: "Hostname of {{ inventory_hostname }} is {{ show_hostname.stdout[0].split('hostname ')[1] }}"
