---
- name: Gather device hostnames using group-based classification
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Get Arista EOS hostname
      arista.eos.eos_command:
        commands: show hostname
      register: device_hostname
      when: "'eos' in group_names"
      ignore_errors: yes

    - name: Get Cisco IOS hostname
      cisco.ios.ios_command:
        commands: show running-config | include hostname
      register: device_hostname
      when: "'ios' in group_names"
      ignore_errors: yes

    - name: Display hostnames
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Hostname: {% if 'eos' in group_names %}{{ device_hostname.stdout[0] | regex_replace('.*hostname is (\\S+).*', '\\1') }}
                   {% elif 'ios' in group_names %}{{ device_hostname.stdout[0] | regex_replace('hostname (\\S+)', '\\1') }}
                   {% else %}UNKNOWN (check group assignment){% endif %}
