---
- name: Configure login banner on Cisco switch
  hosts: u1-int-rtr01
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Set login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          **************************************************
          Unauthorized access is strictly prohibited.
          All activities are monitored and logged.
          **************************************************
        state: present
      register: banner_output

    - name: Display banner configuration result
      debug:
        msg: "{{ banner_output }}"
